name: Model-Generalizability-and-Uncertainty-for-Predicting-Conjugated-Polymer-Solution-Conformation.git


channels:
  - rapidsai
  - conda-forge
  - nvidia
  - rdkit
  - bioconda
  - defaults
  - pip

dependencies:
  - python>=3.11.0
  - rapids=25.04
  - cuda-version=12.0
  - numpy>=1.20.0
  - pandas>=1.0.3
  - pip>=24.0.2
  - rdkit>=2024
  - scipy>=1.4.1
  - scikit-optimize>=0.9.0
  - scikit-learn>=1.5.0
  - matplotlib
  - ipython
  - seaborn
  - xgboost
  - ngboost
  - mordred>=1.2.0
  - Pandarallel
  - openpyxl
  - gpytorch


